# Generated by Django 5.1.7 on 2025-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobswebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
