# Generated by Django 5.1.7 on 2025-04-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobswebapp', '0002_alter_job_is_remote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('company', 'date_posted', 'title'), name='unique_date_company_title'),
        ),
    ]
