name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      #with:
        #python-version: ${{ matrix.python-version }}
    #- name: Install Dependencies
      #run: |
        #python -m pip install --upgrade pip
        #pip install -r requirements.txt
    #- name: Run Tests
      #run: |
        #python manage.py test
    - name: Setup SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ../private.key
          sudo chmod 600 ../private.key
          echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts

    - name: Push to server
      run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} cd myjobboard && git pull && kill -HUP app.pid
    - name: Done
      run: echo "DONE"