name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Make logging files
      run: |
        sudo mkdir -p /var/log/myjobboard/
        sudo touch /var/log/myjobboard/django.app.log
        sudo chmod 666 /var/log/myjobboard/django.app.log
        
    - name: Run Tests
      run: |
        python manage.py check
        python manage.py makemigrations --check --dry-run
        python manage.py test

    - name: Setup SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private.key
          sudo chmod 600 private.key
          echo "${{ secrets.SSH_KNOWN_HOST }}" > ~/.ssh/known_hosts

    - name: Push to server
      run: |
          ssh -i private.key ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} 'cd myjobboard ; git pull ; kill -HUP $(cat app.pid) ; echo "done!"'
    - name: Done
      run: echo "DONE"
